name: EPG Update

on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * *" # every day at 3:30am UTC (8:00am IST)
  push:
    branches: [ main ]

jobs:

  epg:
    name: EPG Setup
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get EPG Data
      run: chmod +x bin/epg_linux_x64 && ./bin/epg_linux_x64
    
    - name: Update release
      env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        hub release edit -a epg.xml -a epg.xml.gz -m "EPG has been updated."
        

